HilmiApp/urls.py
from django.urls import path
from django.contrib import admin
from .views import *

app_name = 'HilmiApp'

urlpatterns = [
	path('', showRecipe, name="recipe"),
]

ShintaApp/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

app_name = 'ShintaApp'

urlpatterns = [
	path('', index, name="index"),
	path('home/', index, name="index"),
	path('register/', register, name="register"),
	path('login/', login, name="login"),
	path('logout/', logout, name="logout"),
	

]

SulthanApp/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views, models, forms

app_name = 'SulthanApp'

urlpatterns = [
	path('', views.contactUsFunc, name="aboutUs"),
	path('tambahContactUs/', views.tambahContactUs, name="tambahContactUs"),
]

TK2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShintaApp.urls')),
    path('recipe-list/', include('HilmiApp.urls')),
    path('about/', include('SulthanApp.urls')),
    path('', include('ThaliaApp.urls')),
]

ThaliaApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('list_resep/', views.list_resep, name='list_resep'),
]

HilmiApp/models.py
from django.db import models

# Create your models here.

ShintaApp/models.py
from django.db import models

# Create your models here.


class Account(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

SulthanApp/models.py
from django.db import models

# Create your models here.

class ContactUs(models.Model):
    namaInput = models.CharField(max_length=300)
    emailInput = models.CharField(max_length=300)
    noTelpInput = models.CharField(max_length=15)
    messageInput = models.CharField(max_length=300)
    bukti = models.CharField(max_length=300)    

    def __str__(self):
        return self.namaInput

ThaliaApp/models.py
from django.db import models


class UploadModels(models.Model):
    nama_resep = models.CharField(max_length=150)
    bahan_bahan = models.TextField(max_length=500)
    langkah_buat = models.TextField(max_length=500)
    photo = models.ImageField(upload_to='images/')

class UploadPhoto(models.Model):
    photo = models.ImageField(upload_to='images/')
    resep = models.ForeignKey(UploadModels, on_delete=models.CASCADE)

ShintaApp/forms.py
from django import forms
from .models import Account


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(max_length=100, required=True)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    email = forms.EmailField()
    password = forms.CharField(max_length=100, required=True)

SulthanApp/forms.py
from django import forms

class ContactUsForm(forms.Form):
    nama = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'placeholder' : 'Nama Lengkap', 'id' : 'nama'}))
    email = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'placeholder' : 'Email', 'id' : 'email'}))
    noTelp = forms.CharField(max_length=15, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'placeholder' : 'Nomor Telepon', 'id' : 'noTelp'}))
    message = forms.CharField(max_length=1000, widget = forms.Textarea(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control h-25','id' : 'message'}))
    testi = forms.CharField(max_length=1000, widget = forms.Textarea(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'id' : 'testi'}))
    

ThaliaApp/forms.py
from django import forms
from .models import UploadModels

class UploadForms(forms.ModelForm):
    class Meta:
        model = UploadModels
        fields = ['nama_resep', 'bahan_bahan', 'langkah_buat', 'photo',]

        widgets = {
            
        }

HilmiApp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from ThaliaApp.models import UploadModels


# Create your views here.

def showRecipe(request):
	uploadModels = UploadModels.objects.all()
	#content = {
	#	'listResep' : uploadModels,
	#	'listFoto' : uploadPhoto,
	#}
	return render (request, "Recipe List.html", {
		'uploadModels': uploadModels
	})

# def get_data(request, key):
# 	url = 'https://www.googleapis.com/books/v1/volumes?q=' + key
# 	response = requests.get(url)
# 	response_json = response.json()

# 	return JsonResponse(response_json)

ShintaApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import Account
from .forms import LoginForm, RegisterForm

# Create your views here.

def index (request):
    response = {};
    if ("wrongpass" in request.GET):
        response['wrongpass'] = True
    return render (request,"home.html", response)
def register(request):
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            if (authenticate(username=request.POST['username'], email=request.POST['email'], password=request.POST['password'])) is None:
                user = User.objects.create_user(
                    request.POST['username'], request.POST['email'], request.POST['password'])
                user.save()
                auth_login(request, user)
                return redirect('/home/')
    return render(request, 'home.html')

def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.filter(username=username).exists()
        if user:
            is_authenticate = authenticate(
                username=username, password=password)
            if is_authenticate:
                auth_login(request, is_authenticate)
                return redirect('/home/')
        return redirect("/home/?wrongpass")
    return render(request, 'home.html')


@login_required
def logout(request):
    auth_logout(request)
    return redirect('/home/')

SulthanApp/views.py
from django.shortcuts import render, redirect

from django.views.decorators.http import require_POST

from .forms import ContactUsForm
from .models import ContactUs


# Create your views here.
def contactUsFunc(request):
    list_testi = ContactUs.objects.order_by('id')
    form = ContactUsForm()
    context = {'form' : form, 'list_testi' : list_testi}

    return render(request, 'about.html', context)

@require_POST
def tambahContactUs(request):
    form = ContactUsForm(request.POST)

    contactUsInput = ContactUs(namaInput = request.POST['nama'], emailInput = request.POST['email'], noTelpInput = request.POST['noTelp'], messageInput = request.POST['message'], bukti = request.POST['testi'])
    contactUsInput.save()

    return redirect('SulthanApp:aboutUs')

ThaliaApp/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import copy


from .models import UploadModels
from .forms import UploadForms

def upload(request):
        page_upload = UploadModels.objects.all()
        form_upload = UploadForms()
        if request.method == 'POST':
        #     newResep = copy.deepcopy(request.POST)
            form_upload = UploadForms(request.POST, request.FILES)
        #     photo_resep_form = PhotoForms(request.POST, request.FILES)
            if form_upload.is_valid():
                nama_resep = request.POST['nama_resep']
                bahan_bahan = request.POST['bahan_bahan']
                langkah_buat = request.POST['langkah_buat']
                photo = request.FILES['photo']
                new_resep = UploadModels(nama_resep=nama_resep, bahan_bahan=bahan_bahan, langkah_buat=langkah_buat, photo=photo)
                new_resep.save()
                # new_photo = PhotoForms(resep = new_resep, photo = photo_resep_form.cleaned_data['photo'])
                # new_photo.save()
                return render(request, 'upload.html', {
                    'success': True
                })
            return render(request, 'upload.html', {
                'failed': True
            })
        return render(request, 'upload.html', {
            'page_upload': page_upload, 'form' : form_upload
        })

def list_resep(request):
    resep_list = list(UploadModels.objects.values())
    return JsonResponse(resep_list, safe=False)

ShintaApp/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title> Resep Pisan </title>
{% endblock %}
 
{% block content %}
<section id="home1">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'assets/slidesatu.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'assets/slide2.jpg' %}" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section id="home2" class="text-center" style="background-color: #FFEBCD">
    <div class="container">
        <div class="row">
             <div class="col-lg-4">
                 <h1 style="margin-top: 50% ; margin-bottom: 30%; font-size: 3.2em"> ResepPisan </h1>
            </div>
            <div class="col-lg-8">
                <div style="margin-top: 18% ;margin-bottom: 18% ;font-size: 22px;"> Situs ini menyajikan informasi terlengkap mengenai segala hal tentang dunia masak-memasak. Kami berusaha menyajikan langkah-langkah yang mudah dipahami dan praktis, untuk membantu meringankan pekerjaan Anda di dapur. Cocok untuk pemula yang sedang belajar masak, maupun yang sudah mahir namun sering bingung mau masak apa.</div>
            </div>
        </div>
    </div>
</section>
<section id="home3" style="margin-top: 12%; margin-bottom: 12%">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="text-center" style="background-color: #FFF8DC; padding: 10px">
                    <h2 style="margin-top: 10%"> Tips and Trick </h2>
                    <div class="text-justify"> Ada banyak tips yang jarang terpikirkan oleh Anda. Lihat beberapa tips berikut yang dapat membantu pekerjaan dapur jadi lebih mudah dan cepat.</div>
                    <button  id="btn-tips" onclick="lihattips()"style="margin-top: 35px; margin-bottom: 15px; border-radius: 5px"> Lihat Tips</button>
                    <div class="text-justify" id="tipskosong"></div>
                </div>
            </div>
            <div class="col-sm-4">
                    <div class="text-center" style="background-color: #B0E0E6; padding: 10px">
                        <h2 style="margin-top: 10%"> Informasi Gizi </h2>
                        <div class="text-justify"> Mengonsumsi ragam makanan dalam satu porsi, bukan berarti telah mencukupi segala nutrisi. Ada baiknya Anda tahu makanan apa saja yang memiliki kandungan nutrisi sama. </div>
                        <button id="btn-gizi" onclick="infogizi()" style="margin-top: 35px; margin-bottom: 15px; border-radius: 5px"> Lihat Info Gizi </button>
                        <div class="text-justify" id="infogizikosong"></div>
                    </div>
                </div>
            <div class="col-sm-4">
                <div class="text-center" style="background-color: #D8BFD8; padding: 10px">
                    <h2 style="margin-top: 10%"> Top Kuliner Depok </h2>
                    <div class="text-justify"> Apa yang terpikirkan di kepala anda ketika mendengar kata Depok? Universitas Indonesia? sayangnya Depok tidak hanya tentang itu. Depok memiliki beberapa tempat kuliner yang tak kalah menarik</div>
                    <button id="btn-tempat" onclick="lihattempat()" style="margin-top: 15px; margin-bottom: 15px; border-radius: 5px"> Lihat Tempat </button>
                    <div class="text-justify"id="namatempatkosong"></div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/shinta.js' %}"></script>
{% endblock %}

SulthanApp/templates/about.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<title> About Us </title>
	<script type="text/javascript" src="{% static 'js/profil.js' %}"></script>
{% endblock %}
 
{% block content %}
	<div class ="">
		<div  class="container mt-5 mb-5 text-center">
			<h2 class ="text-center mb-5"> About Us </h2>
			<div class="row" id="foto"> 
				<div class ="col-sm-3">
					<img style="width: 250px; height: 250px" src="{% static 'assets/fotoHilmi.jpg'%}" id="fotoHilmi">

					<div class="text-justify text-center" id="hilmi"></div>
				</div>
				<div class ="col-sm-3">
					<img style="width: 250px; height: 250px" src="{% static 'assets/Shinta.jpg'%}" id="fotoShinta">
					<div class="text-justify text-center" id="shinta"></div>
				</div>
				<div class ="col-sm-3">
					<img style="width: 250px; height: 250px" src="{% static 'assets/Thalia.jpg'%}" id="fotoThalia">
					<div class="text-justify text-center" id="thalia"></div>
				</div>
				<div class ="col-sm-3">
					<img style="width: 250px; height: 250px" src="{% static 'assets/lto.jpg'%}" id="fotoSulthan">
					<div class="text-justify text-center" id="sulthan"></div>
				</div> 
			</div>
		</div> 
		<div class="container w-25">
		</div> 
		<div class="container w-25">
			<h2 class="mb-4 text-center"> Contact Us!!! </h2>
			<form method="POST" action="{% url 'SulthanApp:tambahContactUs' %}">
				{% csrf_token %}
				<div class="form-group">
					{{ form.nama }}
				</div>
				
				<div class="form-group">
					{{ form.email }}
				</div>
				
				<div class="form-group">
					{{ form.noTelp }}
				</div>
				
				<div class="form-group">
					<label style="font-size: 1vw" for="message" class="">Pesan</label>
					{{ form.message }}
				</div>

				<div class="form-group">
					<label style="font-size: 1vw" for="testi" class="">Testimoni</label>
					{{ form.testi }}
				</div>
				<div class="text-center">
					<button style="font-size: 1vw" type="submit" class="btn btn-secondary mt-2 mr-2 mb-2">Submit</button>
					<button style="font-size: 1vw" type="reset" class="btn btn-secondary m-2">Reset</button>
				</div>
			</form>

			<div class="container mt-5 mb-5 text-center">
				<h1 class="mb-5">Testimoni</h1>
					{% for i in list_testi %}
						{{ i.bukti }} <p><br></p>
					{% endfor %}
			</div>
{% endblock %}

ThaliaApp/templates/upload.html
{% extends "base.html" %}

{% load static %}

{% block title %}ResepPisan Upload{% endblock %}

{% block content %}

<h1 class="text-center pt-4" onmouseover="style.color='orange'" onmouseout="style.color='black'">Upload Resep</h1>
<div class="container py-4">
    <form action="/upload/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="id_nama_resep">Nama Resep :</label>
                <input class="form-control" type="text" id="nama_resep" name="nama_resep" maxlength="80" required="" id="id_nama_resep">
            </div>
        
            <div class="form-group">
                <label for="id_bahan_bahan">Bahan-bahan :</label>
                <textarea class="form-control" type="text" id="bahan_bahan" name="bahan_bahan" maxlength="500" rows="7" required="" id="id_bahan_bahan"></textarea>
            </div>
    
            <div class="form-group">
                <label for="id_langkah_buat">Langkah :</label>
                <textarea class="form-control" type="text" id="langkah_buat" name="langkah_buat" maxlength="1000" rows="9" required="" id="id_langkah_buat"></textarea>
            </div>
            
            <div class="form-group">
                <label for="id_photo_resep">Foto :</label><br>
                <input type="file" name="photo" accept="image/*" required="" id="id_photo">
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </div>
    </form>
</div>
    
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'jquery.js' %}"></script>
{% endblock %}

templates/Recipe List.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  	<script type="text/javascript" src="{% static 'jsfile.js' %}"></script>
	<title> Recipe List </title>
	<script>
// When the user clicks on <div>, open the popup
function myFunction() {
  var popup = document.getElementById("myPopup");
  popup.classList.toggle("show");
}
</script>
{% endblock %}
 
{% block content %}
<section style="overflow-x: hidden;">
	<div class="row">
		<div class="text-center" style="margin: auto;">
			<input style="width: auto; margin-top: 10%;" id="input" type="text" placeholder="Cari Resep">
			<input id="button" 	type="submit" value="Cari">
		</div>
<!-- 		<div class="col">
			<div class="row">
			</div>
			<div class="row">
			</div>
		</div> -->
	</div>
	<div  class="row" style="float: right; padding-right: 10%;">
		<div class="popup" type="button" style="border-radius:50%" onclick="myFunction()">?
  <span class="popuptext" id="myPopup">Resep belum tersedia</span>
</div>
	</div>
</section>
<section style="padding: 2%;">
	<center><STRONG>DAFTAR RESEP<STRONG></center>
	<a><center><br></center> </a>

	 <div class="card-group row ml-4 mr-4" id="sp_container">
                {% for resep in uploadModels %}
                    <div class="col-xl-3 col-md-4 col-12 mb-4" id="sp_card">
                        <div class="card h-100">
                            <div class="card-body">
                                <h4 class="card-title">JUDUL</h4>
                                <p class="card-text">Nama Resep: {{ resep.nama_resep }}</p>
                                <p class="card-text">Bahan: {{ resep.bahan_bahan }}</p>
                                <button class="submit">Check</button>                                       
                            </div>
                    </div>
                    </div>
                {% endfor %}
            </div>



</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE>
<html>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	{% block styles %}{% endblock %}

<body>
	<nav class="navbar-fixed navbar-expand-md navbar-light " style="background-color: #CD853F;">
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
 	  </button>
  	<div class="collapse navbar-collapse" id="navbarNavDropdown" >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="navbar-brand" href="/home/"; style="font-size: 20px ; color : white; font-weight: bold ;padding: 10px"> ResepPisan </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/recipe-list/" style="font-size: 20px ; color : white;font-weight: bold; padding: 10px"> Resep</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/upload/" style="font-size: 20px; color : white; font-weight: bold; padding: 10px"> Upload Resep</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about/" style="font-size: 20px ; color : white; font-weight: bold; padding: 10px"> About Us</a>
        </li>
         {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-link" href="/logout/" style="font-size: 20px ; color : white; font-weight: bold; padding: 10px"> logout</a>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/register/" data-toggle="modal" data-target="#signupModal"style="font-size: 20px ; color : white; font-weight: bold; padding: 10px"> Sign Up </a>
              <div class = "modal fade" role="dialog" id="signupModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type ="button" class = "close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class = "modal-body">
                          {% if user.is_authenticated %}
                          <h1 class="px-5 pt-5">Hi {{ user.username }}, you're already registered.</h1>
                          <a href="/" class="px-5">Back to homepage</a>
                          {% else %}
                          <form method="POST" action="/register/">
                            {% csrf_token %}
                            <table class="table">
                              <tr>
                                <td><label for="id_username" id="labeluname">Username</label></td>
                                <td><input id="id_username"name="username" type="text" class="form-control"></td>
                              </tr>
                              <tr>
                                <td><label for="id_email">Email</label></td>
                                <td><input id="id_email" name="email" type="email" class="form-control" required></td>
                              </tr>
                              <tr>
                                <td><label for="id_password" id ="labelpw">Password</label></td>
                                <td><input id="id_password" name="password" type="password" class="form-control"></td>
                              </tr>
                            </table>
                            <div class="modal-footer">
                            <input type="submit" class="btn btn-success" value="Register">
                          </div>
                          </form>
                         
                            {% endif %}
                        </div>
                   </div>
              </li>

            <li class="nav-item">
                <a class="nav-link" href="/login/" data-toggle="modal" data-target="#loginModal" style="font-size: 20px ; color : white; font-weight: bold; padding: 10px"> Login </a>
                <div class = "modal fade" role="dialog" id="loginModal">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type ="button" class = "close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class = "modal-body">
                      <form action="/login/" class="form-popup" id="myForm" method="post">
                      {% csrf_token %}
                      <table class="table">
                        <tr>
                            <td><label for="id_username" id="labeluname">Username</label></td>
                            <td><input id="id_username"name="username" type="text" class="form-control"></td>
                        </tr>
                        <tr>
                            <td><label for="id_password" id ="labelpw">Password</label></td>
                            <td><input id="id_password" name="password" type="password" class="form-control"></td>
                        </tr>
                      </table>
                      <div class="modal-footer">
                      <input type="submit"  value="Login" class="btn btn-success">
                      <input type="hidden" name="next" value="{{ next }}">
                      </form>
                      </div>
              </li>
             {% endif %}
        </ul>
    </div>
</nav>
<div style="min-height: calc(100vh - 184px)">
  {% block content %}{% endblock %}
</div>
  <section id="home4" class="text-center" style="background-color: #CD853F">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h5 style="margin-top: 10%;"> Contact Us at : support@reseppisan.com</h5>
            </div>
            <div class="col-lg-6">
                <h5 style="margin-top: 7%"> Tentang Kami </h5>
                <p> Website ini dibuat oleh mahahsiwa Perancangan dan Pemograman Website tahun 2019 Kelas E</p>
            </div>
        </div>
    </div>
</section>

  {% block footer %}{% endblock %}
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  	{% block scripts %}{% endblock %}
    {% if wrongpass %}
    <script>
      $( document ).ready(function() {
        alert('Password salah');
      });
    </script>
    {% endif %}
</body>